<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Elastic.Clients.Elasticsearch" Version="8.15.10" />
    <PackageReference Include="MediatR" Version="12.4.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Pereprodai.Shared\Pereprodai.Shared.csproj" />
  </ItemGroup>

</Project>
