// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pereprodai.Catalog.Infrastructure;

#nullable disable

namespace Pereprodai.Catalog.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260402151047_AddAdStatistics")]
    partial class AddAdStatistics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pereprodai.Catalog.Domain.Entities.Ad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("ads", "catalog");
                });

            modelBuilder.Entity("Pereprodai.Catalog.Infrastructure.Entities.AdStatistics", b =>
                {
                    b.Property<Guid>("AdId")
                        .HasColumnType("uuid");

                    b.Property<long>("Views")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.HasKey("AdId");

                    b.ToTable("adStatistics", "catalog");
                });

            modelBuilder.Entity("Pereprodai.Catalog.Domain.Entities.Ad", b =>
                {
                    b.OwnsOne("Pereprodai.Catalog.Domain.ValueObjects.ContactInfo", "ContactInfo", b1 =>
                        {
                            b1.Property<Guid>("AdId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Email")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasMaxLength(14)
                                .HasColumnType("character varying(14)");

                            b1.HasKey("AdId");

                            b1.ToTable("ads", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("AdId");
                        });

                    b.OwnsOne("Pereprodai.Catalog.Domain.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("AdId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.HasKey("AdId");

                            b1.ToTable("ads", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("AdId");
                        });

                    b.OwnsOne("Pereprodai.Catalog.Domain.ValueObjects.Price", "Price", b1 =>
                        {
                            b1.Property<Guid>("AdId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<int>("Currency")
                                .HasColumnType("integer");

                            b1.HasKey("AdId");

                            b1.ToTable("ads", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("AdId");
                        });

                    b.Navigation("ContactInfo")
                        .IsRequired();

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("Price")
                        .IsRequired();
                });

            modelBuilder.Entity("Pereprodai.Catalog.Infrastructure.Entities.AdStatistics", b =>
                {
                    b.HasOne("Pereprodai.Catalog.Domain.Entities.Ad", null)
                        .WithOne()
                        .HasForeignKey("Pereprodai.Catalog.Infrastructure.Entities.AdStatistics", "AdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
