// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pereprodai.Moderation.Infrastructure;

#nullable disable

namespace Pereprodai.Moderation.Migrations
{
    [DbContext(typeof(ModerationDbContext))]
    [Migration("20260305121421_AddModerationTaskAndAdReadModel")]
    partial class AddModerationTaskAndAdReadModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("moderation")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pereprodai.Moderation.Domain.Entities.ModerationTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModeratorId")
                        .HasColumnType("uuid");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdId");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("moderation_tasks", "moderation");
                });

            modelBuilder.Entity("Pereprodai.Moderation.Infrastructure.ReadModels.AdReadModel", b =>
                {
                    b.Property<Guid>("AdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactInfoEmail")
                        .HasColumnType("text");

                    b.Property<string>("ContactInfoPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LocationCity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PriceAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("PriceCurrency")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("AdId");

                    b.ToTable("ads_read_model", "moderation");
                });

            modelBuilder.Entity("Pereprodai.Moderation.Domain.Entities.ModerationTask", b =>
                {
                    b.HasOne("Pereprodai.Moderation.Infrastructure.ReadModels.AdReadModel", null)
                        .WithMany("ModerationTasks")
                        .HasForeignKey("AdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pereprodai.Moderation.Infrastructure.ReadModels.AdReadModel", b =>
                {
                    b.Navigation("ModerationTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
